# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import basecamp_pb2 as basecamp__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in basecamp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BasecampStub(object):
    """=== SERVICE DEFINITION ===
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handle = channel.unary_unary(
                '/basecamp.Basecamp/Handle',
                request_serializer=basecamp__pb2.Request.SerializeToString,
                response_deserializer=basecamp__pb2.Result.FromString,
                _registered_method=True)
        self.InitQuery = channel.unary_unary(
                '/basecamp.Basecamp/InitQuery',
                request_serializer=basecamp__pb2.InitRequest.SerializeToString,
                response_deserializer=basecamp__pb2.Chunk.FromString,
                _registered_method=True)
        self.GetChunk = channel.unary_unary(
                '/basecamp.Basecamp/GetChunk',
                request_serializer=basecamp__pb2.ChunkRequest.SerializeToString,
                response_deserializer=basecamp__pb2.Chunk.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/basecamp.Basecamp/Cancel',
                request_serializer=basecamp__pb2.CancelRequest.SerializeToString,
                response_deserializer=basecamp__pb2.CancelReply.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/basecamp.Basecamp/Health',
                request_serializer=basecamp__pb2.HealthRequest.SerializeToString,
                response_deserializer=basecamp__pb2.HealthReply.FromString,
                _registered_method=True)


class BasecampServicer(object):
    """=== SERVICE DEFINITION ===
    """

    def Handle(self, request, context):
        """Legacy API (backward compatibility)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitQuery(self, request, context):
        """New chunked API
        starts query, returns first chunk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChunk(self, request, context):
        """retrieves subsequent chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """cancels ongoing request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BasecampServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handle': grpc.unary_unary_rpc_method_handler(
                    servicer.Handle,
                    request_deserializer=basecamp__pb2.Request.FromString,
                    response_serializer=basecamp__pb2.Result.SerializeToString,
            ),
            'InitQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.InitQuery,
                    request_deserializer=basecamp__pb2.InitRequest.FromString,
                    response_serializer=basecamp__pb2.Chunk.SerializeToString,
            ),
            'GetChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChunk,
                    request_deserializer=basecamp__pb2.ChunkRequest.FromString,
                    response_serializer=basecamp__pb2.Chunk.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=basecamp__pb2.CancelRequest.FromString,
                    response_serializer=basecamp__pb2.CancelReply.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=basecamp__pb2.HealthRequest.FromString,
                    response_serializer=basecamp__pb2.HealthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'basecamp.Basecamp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('basecamp.Basecamp', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Basecamp(object):
    """=== SERVICE DEFINITION ===
    """

    @staticmethod
    def Handle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/basecamp.Basecamp/Handle',
            basecamp__pb2.Request.SerializeToString,
            basecamp__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/basecamp.Basecamp/InitQuery',
            basecamp__pb2.InitRequest.SerializeToString,
            basecamp__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/basecamp.Basecamp/GetChunk',
            basecamp__pb2.ChunkRequest.SerializeToString,
            basecamp__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/basecamp.Basecamp/Cancel',
            basecamp__pb2.CancelRequest.SerializeToString,
            basecamp__pb2.CancelReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/basecamp.Basecamp/Health',
            basecamp__pb2.HealthRequest.SerializeToString,
            basecamp__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
