# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basecamp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'basecamp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x61secamp.proto\x12\x08\x62\x61secamp\"N\n\x07Request\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x1e\n\x06target\x18\x02 \x01(\x0e\x32\x0e.basecamp.Team\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\">\n\x06Result\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\ncompute_ms\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\x0f\n\rHealthRequest\"\x1b\n\x0bHealthReply\x12\x0c\n\x04node\x18\x01 \x01(\t*J\n\x04Team\x12\x14\n\x10TEAM_UNSPECIFIED\x10\x00\x12\x0e\n\nTEAM_GREEN\x10\x01\x12\r\n\tTEAM_PINK\x10\x02\x12\r\n\tTEAM_BOTH\x10\x03\x32s\n\x08\x42\x61secamp\x12-\n\x06Handle\x12\x11.basecamp.Request\x1a\x10.basecamp.Result\x12\x38\n\x06Health\x12\x17.basecamp.HealthRequest\x1a\x15.basecamp.HealthReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basecamp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEAM']._serialized_start=218
  _globals['_TEAM']._serialized_end=292
  _globals['_REQUEST']._serialized_start=28
  _globals['_REQUEST']._serialized_end=106
  _globals['_RESULT']._serialized_start=108
  _globals['_RESULT']._serialized_end=170
  _globals['_HEALTHREQUEST']._serialized_start=172
  _globals['_HEALTHREQUEST']._serialized_end=187
  _globals['_HEALTHREPLY']._serialized_start=189
  _globals['_HEALTHREPLY']._serialized_end=216
  _globals['_BASECAMP']._serialized_start=294
  _globals['_BASECAMP']._serialized_end=409
# @@protoc_insertion_point(module_scope)
