# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: topology.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'topology.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etopology.proto\x12\x04topo\"\x92\x01\n\x04Node\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x11\n\tis_leader\x18\x04 \x01(\x08\x12\x16\n\x0eis_team_leader\x18\x05 \x01(\x08\x12\x0c\n\x04team\x18\x06 \x01(\t\x12\x11\n\tneighbors\x18\x07 \x03(\t\x12\x14\n\x0cmax_inflight\x18\x08 \x01(\x05\"%\n\x08Topology\x12\x19\n\x05nodes\x18\x01 \x03(\x0b\x32\n.topo.Nodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'topology_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODE']._serialized_start=25
  _globals['_NODE']._serialized_end=171
  _globals['_TOPOLOGY']._serialized_start=173
  _globals['_TOPOLOGY']._serialized_end=210
# @@protoc_insertion_point(module_scope)
