// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: basecamp.proto
#ifndef GRPC_basecamp_2eproto__INCLUDED
#define GRPC_basecamp_2eproto__INCLUDED

#include "basecamp.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace basecamp {

// === SERVICE DEFINITION ===
class Basecamp final {
 public:
  static constexpr char const* service_full_name() {
    return "basecamp.Basecamp";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Legacy API (backward compatibility)
    virtual ::grpc::Status Handle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::basecamp::Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Result>> AsyncHandle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Result>>(AsyncHandleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Result>> PrepareAsyncHandle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Result>>(PrepareAsyncHandleRaw(context, request, cq));
    }
    // New chunked API
    virtual ::grpc::Status InitQuery(::grpc::ClientContext* context, const ::basecamp::InitRequest& request, ::basecamp::Chunk* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Chunk>> AsyncInitQuery(::grpc::ClientContext* context, const ::basecamp::InitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Chunk>>(AsyncInitQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Chunk>> PrepareAsyncInitQuery(::grpc::ClientContext* context, const ::basecamp::InitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Chunk>>(PrepareAsyncInitQueryRaw(context, request, cq));
    }
    // starts query, returns first chunk
    virtual ::grpc::Status GetChunk(::grpc::ClientContext* context, const ::basecamp::ChunkRequest& request, ::basecamp::Chunk* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Chunk>> AsyncGetChunk(::grpc::ClientContext* context, const ::basecamp::ChunkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Chunk>>(AsyncGetChunkRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Chunk>> PrepareAsyncGetChunk(::grpc::ClientContext* context, const ::basecamp::ChunkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Chunk>>(PrepareAsyncGetChunkRaw(context, request, cq));
    }
    // retrieves subsequent chunks
    virtual ::grpc::Status Cancel(::grpc::ClientContext* context, const ::basecamp::CancelRequest& request, ::basecamp::CancelReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::CancelReply>> AsyncCancel(::grpc::ClientContext* context, const ::basecamp::CancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::CancelReply>>(AsyncCancelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::CancelReply>> PrepareAsyncCancel(::grpc::ClientContext* context, const ::basecamp::CancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::CancelReply>>(PrepareAsyncCancelRaw(context, request, cq));
    }
    // cancels ongoing request
    // Health check
    virtual ::grpc::Status Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::basecamp::HealthReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::HealthReply>> AsyncHealth(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::HealthReply>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::HealthReply>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::HealthReply>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Legacy API (backward compatibility)
      virtual void Handle(::grpc::ClientContext* context, const ::basecamp::Request* request, ::basecamp::Result* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Handle(::grpc::ClientContext* context, const ::basecamp::Request* request, ::basecamp::Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // New chunked API
      virtual void InitQuery(::grpc::ClientContext* context, const ::basecamp::InitRequest* request, ::basecamp::Chunk* response, std::function<void(::grpc::Status)>) = 0;
      virtual void InitQuery(::grpc::ClientContext* context, const ::basecamp::InitRequest* request, ::basecamp::Chunk* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // starts query, returns first chunk
      virtual void GetChunk(::grpc::ClientContext* context, const ::basecamp::ChunkRequest* request, ::basecamp::Chunk* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetChunk(::grpc::ClientContext* context, const ::basecamp::ChunkRequest* request, ::basecamp::Chunk* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // retrieves subsequent chunks
      virtual void Cancel(::grpc::ClientContext* context, const ::basecamp::CancelRequest* request, ::basecamp::CancelReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Cancel(::grpc::ClientContext* context, const ::basecamp::CancelRequest* request, ::basecamp::CancelReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // cancels ongoing request
      // Health check
      virtual void Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Result>* AsyncHandleRaw(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Result>* PrepareAsyncHandleRaw(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Chunk>* AsyncInitQueryRaw(::grpc::ClientContext* context, const ::basecamp::InitRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Chunk>* PrepareAsyncInitQueryRaw(::grpc::ClientContext* context, const ::basecamp::InitRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Chunk>* AsyncGetChunkRaw(::grpc::ClientContext* context, const ::basecamp::ChunkRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Chunk>* PrepareAsyncGetChunkRaw(::grpc::ClientContext* context, const ::basecamp::ChunkRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::CancelReply>* AsyncCancelRaw(::grpc::ClientContext* context, const ::basecamp::CancelRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::CancelReply>* PrepareAsyncCancelRaw(::grpc::ClientContext* context, const ::basecamp::CancelRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::HealthReply>* AsyncHealthRaw(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::HealthReply>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Handle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::basecamp::Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Result>> AsyncHandle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Result>>(AsyncHandleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Result>> PrepareAsyncHandle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Result>>(PrepareAsyncHandleRaw(context, request, cq));
    }
    ::grpc::Status InitQuery(::grpc::ClientContext* context, const ::basecamp::InitRequest& request, ::basecamp::Chunk* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Chunk>> AsyncInitQuery(::grpc::ClientContext* context, const ::basecamp::InitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Chunk>>(AsyncInitQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Chunk>> PrepareAsyncInitQuery(::grpc::ClientContext* context, const ::basecamp::InitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Chunk>>(PrepareAsyncInitQueryRaw(context, request, cq));
    }
    ::grpc::Status GetChunk(::grpc::ClientContext* context, const ::basecamp::ChunkRequest& request, ::basecamp::Chunk* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Chunk>> AsyncGetChunk(::grpc::ClientContext* context, const ::basecamp::ChunkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Chunk>>(AsyncGetChunkRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Chunk>> PrepareAsyncGetChunk(::grpc::ClientContext* context, const ::basecamp::ChunkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Chunk>>(PrepareAsyncGetChunkRaw(context, request, cq));
    }
    ::grpc::Status Cancel(::grpc::ClientContext* context, const ::basecamp::CancelRequest& request, ::basecamp::CancelReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::CancelReply>> AsyncCancel(::grpc::ClientContext* context, const ::basecamp::CancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::CancelReply>>(AsyncCancelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::CancelReply>> PrepareAsyncCancel(::grpc::ClientContext* context, const ::basecamp::CancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::CancelReply>>(PrepareAsyncCancelRaw(context, request, cq));
    }
    ::grpc::Status Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::basecamp::HealthReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>> AsyncHealth(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Handle(::grpc::ClientContext* context, const ::basecamp::Request* request, ::basecamp::Result* response, std::function<void(::grpc::Status)>) override;
      void Handle(::grpc::ClientContext* context, const ::basecamp::Request* request, ::basecamp::Result* response, ::grpc::ClientUnaryReactor* reactor) override;
      void InitQuery(::grpc::ClientContext* context, const ::basecamp::InitRequest* request, ::basecamp::Chunk* response, std::function<void(::grpc::Status)>) override;
      void InitQuery(::grpc::ClientContext* context, const ::basecamp::InitRequest* request, ::basecamp::Chunk* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetChunk(::grpc::ClientContext* context, const ::basecamp::ChunkRequest* request, ::basecamp::Chunk* response, std::function<void(::grpc::Status)>) override;
      void GetChunk(::grpc::ClientContext* context, const ::basecamp::ChunkRequest* request, ::basecamp::Chunk* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Cancel(::grpc::ClientContext* context, const ::basecamp::CancelRequest* request, ::basecamp::CancelReply* response, std::function<void(::grpc::Status)>) override;
      void Cancel(::grpc::ClientContext* context, const ::basecamp::CancelRequest* request, ::basecamp::CancelReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response, std::function<void(::grpc::Status)>) override;
      void Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::basecamp::Result>* AsyncHandleRaw(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basecamp::Result>* PrepareAsyncHandleRaw(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basecamp::Chunk>* AsyncInitQueryRaw(::grpc::ClientContext* context, const ::basecamp::InitRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basecamp::Chunk>* PrepareAsyncInitQueryRaw(::grpc::ClientContext* context, const ::basecamp::InitRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basecamp::Chunk>* AsyncGetChunkRaw(::grpc::ClientContext* context, const ::basecamp::ChunkRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basecamp::Chunk>* PrepareAsyncGetChunkRaw(::grpc::ClientContext* context, const ::basecamp::ChunkRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basecamp::CancelReply>* AsyncCancelRaw(::grpc::ClientContext* context, const ::basecamp::CancelRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basecamp::CancelReply>* PrepareAsyncCancelRaw(::grpc::ClientContext* context, const ::basecamp::CancelRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>* AsyncHealthRaw(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Handle_;
    const ::grpc::internal::RpcMethod rpcmethod_InitQuery_;
    const ::grpc::internal::RpcMethod rpcmethod_GetChunk_;
    const ::grpc::internal::RpcMethod rpcmethod_Cancel_;
    const ::grpc::internal::RpcMethod rpcmethod_Health_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Legacy API (backward compatibility)
    virtual ::grpc::Status Handle(::grpc::ServerContext* context, const ::basecamp::Request* request, ::basecamp::Result* response);
    // New chunked API
    virtual ::grpc::Status InitQuery(::grpc::ServerContext* context, const ::basecamp::InitRequest* request, ::basecamp::Chunk* response);
    // starts query, returns first chunk
    virtual ::grpc::Status GetChunk(::grpc::ServerContext* context, const ::basecamp::ChunkRequest* request, ::basecamp::Chunk* response);
    // retrieves subsequent chunks
    virtual ::grpc::Status Cancel(::grpc::ServerContext* context, const ::basecamp::CancelRequest* request, ::basecamp::CancelReply* response);
    // cancels ongoing request
    // Health check
    virtual ::grpc::Status Health(::grpc::ServerContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Handle() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handle(::grpc::ServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandle(::grpc::ServerContext* context, ::basecamp::Request* request, ::grpc::ServerAsyncResponseWriter< ::basecamp::Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_InitQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_InitQuery() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_InitQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitQuery(::grpc::ServerContext* /*context*/, const ::basecamp::InitRequest* /*request*/, ::basecamp::Chunk* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInitQuery(::grpc::ServerContext* context, ::basecamp::InitRequest* request, ::grpc::ServerAsyncResponseWriter< ::basecamp::Chunk>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetChunk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetChunk() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetChunk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetChunk(::grpc::ServerContext* /*context*/, const ::basecamp::ChunkRequest* /*request*/, ::basecamp::Chunk* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetChunk(::grpc::ServerContext* context, ::basecamp::ChunkRequest* request, ::grpc::ServerAsyncResponseWriter< ::basecamp::Chunk>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Cancel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Cancel() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Cancel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Cancel(::grpc::ServerContext* /*context*/, const ::basecamp::CancelRequest* /*request*/, ::basecamp::CancelReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancel(::grpc::ServerContext* context, ::basecamp::CancelRequest* request, ::grpc::ServerAsyncResponseWriter< ::basecamp::CancelReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Health() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::basecamp::HealthRequest* request, ::grpc::ServerAsyncResponseWriter< ::basecamp::HealthReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Handle<WithAsyncMethod_InitQuery<WithAsyncMethod_GetChunk<WithAsyncMethod_Cancel<WithAsyncMethod_Health<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Handle() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::basecamp::Request, ::basecamp::Result>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::basecamp::Request* request, ::basecamp::Result* response) { return this->Handle(context, request, response); }));}
    void SetMessageAllocatorFor_Handle(
        ::grpc::MessageAllocator< ::basecamp::Request, ::basecamp::Result>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::basecamp::Request, ::basecamp::Result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handle(::grpc::ServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Handle(
      ::grpc::CallbackServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_InitQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_InitQuery() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::basecamp::InitRequest, ::basecamp::Chunk>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::basecamp::InitRequest* request, ::basecamp::Chunk* response) { return this->InitQuery(context, request, response); }));}
    void SetMessageAllocatorFor_InitQuery(
        ::grpc::MessageAllocator< ::basecamp::InitRequest, ::basecamp::Chunk>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::basecamp::InitRequest, ::basecamp::Chunk>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_InitQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitQuery(::grpc::ServerContext* /*context*/, const ::basecamp::InitRequest* /*request*/, ::basecamp::Chunk* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InitQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::basecamp::InitRequest* /*request*/, ::basecamp::Chunk* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetChunk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetChunk() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::basecamp::ChunkRequest, ::basecamp::Chunk>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::basecamp::ChunkRequest* request, ::basecamp::Chunk* response) { return this->GetChunk(context, request, response); }));}
    void SetMessageAllocatorFor_GetChunk(
        ::grpc::MessageAllocator< ::basecamp::ChunkRequest, ::basecamp::Chunk>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::basecamp::ChunkRequest, ::basecamp::Chunk>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetChunk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetChunk(::grpc::ServerContext* /*context*/, const ::basecamp::ChunkRequest* /*request*/, ::basecamp::Chunk* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetChunk(
      ::grpc::CallbackServerContext* /*context*/, const ::basecamp::ChunkRequest* /*request*/, ::basecamp::Chunk* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Cancel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Cancel() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::basecamp::CancelRequest, ::basecamp::CancelReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::basecamp::CancelRequest* request, ::basecamp::CancelReply* response) { return this->Cancel(context, request, response); }));}
    void SetMessageAllocatorFor_Cancel(
        ::grpc::MessageAllocator< ::basecamp::CancelRequest, ::basecamp::CancelReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::basecamp::CancelRequest, ::basecamp::CancelReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Cancel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Cancel(::grpc::ServerContext* /*context*/, const ::basecamp::CancelRequest* /*request*/, ::basecamp::CancelReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Cancel(
      ::grpc::CallbackServerContext* /*context*/, const ::basecamp::CancelRequest* /*request*/, ::basecamp::CancelReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Health() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::basecamp::HealthRequest, ::basecamp::HealthReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response) { return this->Health(context, request, response); }));}
    void SetMessageAllocatorFor_Health(
        ::grpc::MessageAllocator< ::basecamp::HealthRequest, ::basecamp::HealthReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::basecamp::HealthRequest, ::basecamp::HealthReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Handle<WithCallbackMethod_InitQuery<WithCallbackMethod_GetChunk<WithCallbackMethod_Cancel<WithCallbackMethod_Health<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Handle() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handle(::grpc::ServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_InitQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_InitQuery() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_InitQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitQuery(::grpc::ServerContext* /*context*/, const ::basecamp::InitRequest* /*request*/, ::basecamp::Chunk* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetChunk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetChunk() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetChunk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetChunk(::grpc::ServerContext* /*context*/, const ::basecamp::ChunkRequest* /*request*/, ::basecamp::Chunk* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Cancel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Cancel() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Cancel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Cancel(::grpc::ServerContext* /*context*/, const ::basecamp::CancelRequest* /*request*/, ::basecamp::CancelReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Health() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Handle() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handle(::grpc::ServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandle(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_InitQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_InitQuery() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_InitQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitQuery(::grpc::ServerContext* /*context*/, const ::basecamp::InitRequest* /*request*/, ::basecamp::Chunk* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInitQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetChunk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetChunk() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetChunk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetChunk(::grpc::ServerContext* /*context*/, const ::basecamp::ChunkRequest* /*request*/, ::basecamp::Chunk* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetChunk(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Cancel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Cancel() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Cancel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Cancel(::grpc::ServerContext* /*context*/, const ::basecamp::CancelRequest* /*request*/, ::basecamp::CancelReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancel(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Health() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Handle() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Handle(context, request, response); }));
    }
    ~WithRawCallbackMethod_Handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handle(::grpc::ServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Handle(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_InitQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_InitQuery() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->InitQuery(context, request, response); }));
    }
    ~WithRawCallbackMethod_InitQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitQuery(::grpc::ServerContext* /*context*/, const ::basecamp::InitRequest* /*request*/, ::basecamp::Chunk* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InitQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetChunk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetChunk() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetChunk(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetChunk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetChunk(::grpc::ServerContext* /*context*/, const ::basecamp::ChunkRequest* /*request*/, ::basecamp::Chunk* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetChunk(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Cancel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Cancel() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Cancel(context, request, response); }));
    }
    ~WithRawCallbackMethod_Cancel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Cancel(::grpc::ServerContext* /*context*/, const ::basecamp::CancelRequest* /*request*/, ::basecamp::CancelReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Cancel(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Health() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Health(context, request, response); }));
    }
    ~WithRawCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Handle() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::basecamp::Request, ::basecamp::Result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::basecamp::Request, ::basecamp::Result>* streamer) {
                       return this->StreamedHandle(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Handle(::grpc::ServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHandle(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::basecamp::Request,::basecamp::Result>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_InitQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_InitQuery() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::basecamp::InitRequest, ::basecamp::Chunk>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::basecamp::InitRequest, ::basecamp::Chunk>* streamer) {
                       return this->StreamedInitQuery(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_InitQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status InitQuery(::grpc::ServerContext* /*context*/, const ::basecamp::InitRequest* /*request*/, ::basecamp::Chunk* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInitQuery(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::basecamp::InitRequest,::basecamp::Chunk>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetChunk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetChunk() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::basecamp::ChunkRequest, ::basecamp::Chunk>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::basecamp::ChunkRequest, ::basecamp::Chunk>* streamer) {
                       return this->StreamedGetChunk(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetChunk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetChunk(::grpc::ServerContext* /*context*/, const ::basecamp::ChunkRequest* /*request*/, ::basecamp::Chunk* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetChunk(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::basecamp::ChunkRequest,::basecamp::Chunk>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Cancel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Cancel() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::basecamp::CancelRequest, ::basecamp::CancelReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::basecamp::CancelRequest, ::basecamp::CancelReply>* streamer) {
                       return this->StreamedCancel(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Cancel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Cancel(::grpc::ServerContext* /*context*/, const ::basecamp::CancelRequest* /*request*/, ::basecamp::CancelReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCancel(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::basecamp::CancelRequest,::basecamp::CancelReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Health() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::basecamp::HealthRequest, ::basecamp::HealthReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::basecamp::HealthRequest, ::basecamp::HealthReply>* streamer) {
                       return this->StreamedHealth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHealth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::basecamp::HealthRequest,::basecamp::HealthReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Handle<WithStreamedUnaryMethod_InitQuery<WithStreamedUnaryMethod_GetChunk<WithStreamedUnaryMethod_Cancel<WithStreamedUnaryMethod_Health<Service > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Handle<WithStreamedUnaryMethod_InitQuery<WithStreamedUnaryMethod_GetChunk<WithStreamedUnaryMethod_Cancel<WithStreamedUnaryMethod_Health<Service > > > > > StreamedService;
};

}  // namespace basecamp


#endif  // GRPC_basecamp_2eproto__INCLUDED
