// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: basecamp.proto

#include "basecamp.pb.h"
#include "basecamp.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace basecamp {

static const char* Basecamp_method_names[] = {
  "/basecamp.Basecamp/Handle",
  "/basecamp.Basecamp/Health",
};

std::unique_ptr< Basecamp::Stub> Basecamp::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Basecamp::Stub> stub(new Basecamp::Stub(channel, options));
  return stub;
}

Basecamp::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Handle_(Basecamp_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Health_(Basecamp_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Basecamp::Stub::Handle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::basecamp::Result* response) {
  return ::grpc::internal::BlockingUnaryCall< ::basecamp::Request, ::basecamp::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Handle_, context, request, response);
}

void Basecamp::Stub::async::Handle(::grpc::ClientContext* context, const ::basecamp::Request* request, ::basecamp::Result* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::basecamp::Request, ::basecamp::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Handle_, context, request, response, std::move(f));
}

void Basecamp::Stub::async::Handle(::grpc::ClientContext* context, const ::basecamp::Request* request, ::basecamp::Result* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Handle_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::basecamp::Result>* Basecamp::Stub::PrepareAsyncHandleRaw(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::basecamp::Result, ::basecamp::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Handle_, context, request);
}

::grpc::ClientAsyncResponseReader< ::basecamp::Result>* Basecamp::Stub::AsyncHandleRaw(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Basecamp::Stub::Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::basecamp::HealthReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::basecamp::HealthRequest, ::basecamp::HealthReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Health_, context, request, response);
}

void Basecamp::Stub::async::Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::basecamp::HealthRequest, ::basecamp::HealthReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, std::move(f));
}

void Basecamp::Stub::async::Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>* Basecamp::Stub::PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::basecamp::HealthReply, ::basecamp::HealthRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Health_, context, request);
}

::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>* Basecamp::Stub::AsyncHealthRaw(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthRaw(context, request, cq);
  result->StartCall();
  return result;
}

Basecamp::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Basecamp_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Basecamp::Service, ::basecamp::Request, ::basecamp::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Basecamp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::basecamp::Request* req,
             ::basecamp::Result* resp) {
               return service->Handle(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Basecamp_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Basecamp::Service, ::basecamp::HealthRequest, ::basecamp::HealthReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Basecamp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::basecamp::HealthRequest* req,
             ::basecamp::HealthReply* resp) {
               return service->Health(ctx, req, resp);
             }, this)));
}

Basecamp::Service::~Service() {
}

::grpc::Status Basecamp::Service::Handle(::grpc::ServerContext* context, const ::basecamp::Request* request, ::basecamp::Result* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Basecamp::Service::Health(::grpc::ServerContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace basecamp
#include <grpcpp/ports_undef.inc>

