// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: basecamp.proto
#ifndef GRPC_basecamp_2eproto__INCLUDED
#define GRPC_basecamp_2eproto__INCLUDED

#include "basecamp.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace basecamp {

class Basecamp final {
 public:
  static constexpr char const* service_full_name() {
    return "basecamp.Basecamp";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Handle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::basecamp::Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Result>> AsyncHandle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Result>>(AsyncHandleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Result>> PrepareAsyncHandle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Result>>(PrepareAsyncHandleRaw(context, request, cq));
    }
    virtual ::grpc::Status Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::basecamp::HealthReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::HealthReply>> AsyncHealth(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::HealthReply>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::HealthReply>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::HealthReply>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Handle(::grpc::ClientContext* context, const ::basecamp::Request* request, ::basecamp::Result* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Handle(::grpc::ClientContext* context, const ::basecamp::Request* request, ::basecamp::Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Result>* AsyncHandleRaw(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::Result>* PrepareAsyncHandleRaw(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::HealthReply>* AsyncHealthRaw(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basecamp::HealthReply>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Handle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::basecamp::Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Result>> AsyncHandle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Result>>(AsyncHandleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Result>> PrepareAsyncHandle(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::Result>>(PrepareAsyncHandleRaw(context, request, cq));
    }
    ::grpc::Status Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::basecamp::HealthReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>> AsyncHealth(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Handle(::grpc::ClientContext* context, const ::basecamp::Request* request, ::basecamp::Result* response, std::function<void(::grpc::Status)>) override;
      void Handle(::grpc::ClientContext* context, const ::basecamp::Request* request, ::basecamp::Result* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response, std::function<void(::grpc::Status)>) override;
      void Health(::grpc::ClientContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::basecamp::Result>* AsyncHandleRaw(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basecamp::Result>* PrepareAsyncHandleRaw(::grpc::ClientContext* context, const ::basecamp::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>* AsyncHealthRaw(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basecamp::HealthReply>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::basecamp::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Handle_;
    const ::grpc::internal::RpcMethod rpcmethod_Health_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Handle(::grpc::ServerContext* context, const ::basecamp::Request* request, ::basecamp::Result* response);
    virtual ::grpc::Status Health(::grpc::ServerContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Handle() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handle(::grpc::ServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandle(::grpc::ServerContext* context, ::basecamp::Request* request, ::grpc::ServerAsyncResponseWriter< ::basecamp::Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Health() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::basecamp::HealthRequest* request, ::grpc::ServerAsyncResponseWriter< ::basecamp::HealthReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Handle<WithAsyncMethod_Health<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Handle() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::basecamp::Request, ::basecamp::Result>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::basecamp::Request* request, ::basecamp::Result* response) { return this->Handle(context, request, response); }));}
    void SetMessageAllocatorFor_Handle(
        ::grpc::MessageAllocator< ::basecamp::Request, ::basecamp::Result>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::basecamp::Request, ::basecamp::Result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handle(::grpc::ServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Handle(
      ::grpc::CallbackServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Health() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::basecamp::HealthRequest, ::basecamp::HealthReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::basecamp::HealthRequest* request, ::basecamp::HealthReply* response) { return this->Health(context, request, response); }));}
    void SetMessageAllocatorFor_Health(
        ::grpc::MessageAllocator< ::basecamp::HealthRequest, ::basecamp::HealthReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::basecamp::HealthRequest, ::basecamp::HealthReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Handle<WithCallbackMethod_Health<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Handle() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handle(::grpc::ServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Health() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Handle() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handle(::grpc::ServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandle(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Health() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Handle() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Handle(context, request, response); }));
    }
    ~WithRawCallbackMethod_Handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Handle(::grpc::ServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Handle(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Health() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Health(context, request, response); }));
    }
    ~WithRawCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Handle() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::basecamp::Request, ::basecamp::Result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::basecamp::Request, ::basecamp::Result>* streamer) {
                       return this->StreamedHandle(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Handle(::grpc::ServerContext* /*context*/, const ::basecamp::Request* /*request*/, ::basecamp::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHandle(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::basecamp::Request,::basecamp::Result>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Health() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::basecamp::HealthRequest, ::basecamp::HealthReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::basecamp::HealthRequest, ::basecamp::HealthReply>* streamer) {
                       return this->StreamedHealth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::basecamp::HealthRequest* /*request*/, ::basecamp::HealthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHealth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::basecamp::HealthRequest,::basecamp::HealthReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Handle<WithStreamedUnaryMethod_Health<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Handle<WithStreamedUnaryMethod_Health<Service > > StreamedService;
};

}  // namespace basecamp


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_basecamp_2eproto__INCLUDED
