// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: topology.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_topology_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_topology_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_topology_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_topology_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_topology_2eproto;
namespace topo {
class Node;
struct NodeDefaultTypeInternal;
extern NodeDefaultTypeInternal _Node_default_instance_;
class Topology;
struct TopologyDefaultTypeInternal;
extern TopologyDefaultTypeInternal _Topology_default_instance_;
}  // namespace topo
PROTOBUF_NAMESPACE_OPEN
template<> ::topo::Node* Arena::CreateMaybeMessage<::topo::Node>(Arena*);
template<> ::topo::Topology* Arena::CreateMaybeMessage<::topo::Topology>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace topo {

// ===================================================================

class Node final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:topo.Node) */ {
 public:
  inline Node() : Node(nullptr) {}
  ~Node() override;
  explicit PROTOBUF_CONSTEXPR Node(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Node(const Node& from);
  Node(Node&& from) noexcept
    : Node() {
    *this = ::std::move(from);
  }

  inline Node& operator=(const Node& from) {
    CopyFrom(from);
    return *this;
  }
  inline Node& operator=(Node&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Node& default_instance() {
    return *internal_default_instance();
  }
  static inline const Node* internal_default_instance() {
    return reinterpret_cast<const Node*>(
               &_Node_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Node& a, Node& b) {
    a.Swap(&b);
  }
  inline void Swap(Node* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Node* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Node* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Node>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Node& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Node& from) {
    Node::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Node* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "topo.Node";
  }
  protected:
  explicit Node(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNeighborsFieldNumber = 7,
    kNameFieldNumber = 1,
    kHostFieldNumber = 2,
    kTeamFieldNumber = 6,
    kPortFieldNumber = 3,
    kIsLeaderFieldNumber = 4,
    kIsTeamLeaderFieldNumber = 5,
    kMaxInflightFieldNumber = 8,
  };
  // repeated string neighbors = 7;
  int neighbors_size() const;
  private:
  int _internal_neighbors_size() const;
  public:
  void clear_neighbors();
  const std::string& neighbors(int index) const;
  std::string* mutable_neighbors(int index);
  void set_neighbors(int index, const std::string& value);
  void set_neighbors(int index, std::string&& value);
  void set_neighbors(int index, const char* value);
  void set_neighbors(int index, const char* value, size_t size);
  std::string* add_neighbors();
  void add_neighbors(const std::string& value);
  void add_neighbors(std::string&& value);
  void add_neighbors(const char* value);
  void add_neighbors(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& neighbors() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_neighbors();
  private:
  const std::string& _internal_neighbors(int index) const;
  std::string* _internal_add_neighbors();
  public:

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string host = 2;
  void clear_host();
  const std::string& host() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_host(ArgT0&& arg0, ArgT... args);
  std::string* mutable_host();
  PROTOBUF_NODISCARD std::string* release_host();
  void set_allocated_host(std::string* host);
  private:
  const std::string& _internal_host() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_host(const std::string& value);
  std::string* _internal_mutable_host();
  public:

  // string team = 6;
  void clear_team();
  const std::string& team() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_team(ArgT0&& arg0, ArgT... args);
  std::string* mutable_team();
  PROTOBUF_NODISCARD std::string* release_team();
  void set_allocated_team(std::string* team);
  private:
  const std::string& _internal_team() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_team(const std::string& value);
  std::string* _internal_mutable_team();
  public:

  // int32 port = 3;
  void clear_port();
  int32_t port() const;
  void set_port(int32_t value);
  private:
  int32_t _internal_port() const;
  void _internal_set_port(int32_t value);
  public:

  // bool is_leader = 4;
  void clear_is_leader();
  bool is_leader() const;
  void set_is_leader(bool value);
  private:
  bool _internal_is_leader() const;
  void _internal_set_is_leader(bool value);
  public:

  // bool is_team_leader = 5;
  void clear_is_team_leader();
  bool is_team_leader() const;
  void set_is_team_leader(bool value);
  private:
  bool _internal_is_team_leader() const;
  void _internal_set_is_team_leader(bool value);
  public:

  // int32 max_inflight = 8;
  void clear_max_inflight();
  int32_t max_inflight() const;
  void set_max_inflight(int32_t value);
  private:
  int32_t _internal_max_inflight() const;
  void _internal_set_max_inflight(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:topo.Node)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> neighbors_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr host_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr team_;
    int32_t port_;
    bool is_leader_;
    bool is_team_leader_;
    int32_t max_inflight_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_topology_2eproto;
};
// -------------------------------------------------------------------

class Topology final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:topo.Topology) */ {
 public:
  inline Topology() : Topology(nullptr) {}
  ~Topology() override;
  explicit PROTOBUF_CONSTEXPR Topology(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Topology(const Topology& from);
  Topology(Topology&& from) noexcept
    : Topology() {
    *this = ::std::move(from);
  }

  inline Topology& operator=(const Topology& from) {
    CopyFrom(from);
    return *this;
  }
  inline Topology& operator=(Topology&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Topology& default_instance() {
    return *internal_default_instance();
  }
  static inline const Topology* internal_default_instance() {
    return reinterpret_cast<const Topology*>(
               &_Topology_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Topology& a, Topology& b) {
    a.Swap(&b);
  }
  inline void Swap(Topology* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Topology* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Topology* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Topology>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Topology& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Topology& from) {
    Topology::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Topology* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "topo.Topology";
  }
  protected:
  explicit Topology(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodesFieldNumber = 1,
  };
  // repeated .topo.Node nodes = 1;
  int nodes_size() const;
  private:
  int _internal_nodes_size() const;
  public:
  void clear_nodes();
  ::topo::Node* mutable_nodes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::topo::Node >*
      mutable_nodes();
  private:
  const ::topo::Node& _internal_nodes(int index) const;
  ::topo::Node* _internal_add_nodes();
  public:
  const ::topo::Node& nodes(int index) const;
  ::topo::Node* add_nodes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::topo::Node >&
      nodes() const;

  // @@protoc_insertion_point(class_scope:topo.Topology)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::topo::Node > nodes_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_topology_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Node

// string name = 1;
inline void Node::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Node::name() const {
  // @@protoc_insertion_point(field_get:topo.Node.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Node::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:topo.Node.name)
}
inline std::string* Node::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:topo.Node.name)
  return _s;
}
inline const std::string& Node::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Node::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Node::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Node::release_name() {
  // @@protoc_insertion_point(field_release:topo.Node.name)
  return _impl_.name_.Release();
}
inline void Node::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:topo.Node.name)
}

// string host = 2;
inline void Node::clear_host() {
  _impl_.host_.ClearToEmpty();
}
inline const std::string& Node::host() const {
  // @@protoc_insertion_point(field_get:topo.Node.host)
  return _internal_host();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Node::set_host(ArgT0&& arg0, ArgT... args) {
 
 _impl_.host_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:topo.Node.host)
}
inline std::string* Node::mutable_host() {
  std::string* _s = _internal_mutable_host();
  // @@protoc_insertion_point(field_mutable:topo.Node.host)
  return _s;
}
inline const std::string& Node::_internal_host() const {
  return _impl_.host_.Get();
}
inline void Node::_internal_set_host(const std::string& value) {
  
  _impl_.host_.Set(value, GetArenaForAllocation());
}
inline std::string* Node::_internal_mutable_host() {
  
  return _impl_.host_.Mutable(GetArenaForAllocation());
}
inline std::string* Node::release_host() {
  // @@protoc_insertion_point(field_release:topo.Node.host)
  return _impl_.host_.Release();
}
inline void Node::set_allocated_host(std::string* host) {
  if (host != nullptr) {
    
  } else {
    
  }
  _impl_.host_.SetAllocated(host, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.host_.IsDefault()) {
    _impl_.host_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:topo.Node.host)
}

// int32 port = 3;
inline void Node::clear_port() {
  _impl_.port_ = 0;
}
inline int32_t Node::_internal_port() const {
  return _impl_.port_;
}
inline int32_t Node::port() const {
  // @@protoc_insertion_point(field_get:topo.Node.port)
  return _internal_port();
}
inline void Node::_internal_set_port(int32_t value) {
  
  _impl_.port_ = value;
}
inline void Node::set_port(int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:topo.Node.port)
}

// bool is_leader = 4;
inline void Node::clear_is_leader() {
  _impl_.is_leader_ = false;
}
inline bool Node::_internal_is_leader() const {
  return _impl_.is_leader_;
}
inline bool Node::is_leader() const {
  // @@protoc_insertion_point(field_get:topo.Node.is_leader)
  return _internal_is_leader();
}
inline void Node::_internal_set_is_leader(bool value) {
  
  _impl_.is_leader_ = value;
}
inline void Node::set_is_leader(bool value) {
  _internal_set_is_leader(value);
  // @@protoc_insertion_point(field_set:topo.Node.is_leader)
}

// bool is_team_leader = 5;
inline void Node::clear_is_team_leader() {
  _impl_.is_team_leader_ = false;
}
inline bool Node::_internal_is_team_leader() const {
  return _impl_.is_team_leader_;
}
inline bool Node::is_team_leader() const {
  // @@protoc_insertion_point(field_get:topo.Node.is_team_leader)
  return _internal_is_team_leader();
}
inline void Node::_internal_set_is_team_leader(bool value) {
  
  _impl_.is_team_leader_ = value;
}
inline void Node::set_is_team_leader(bool value) {
  _internal_set_is_team_leader(value);
  // @@protoc_insertion_point(field_set:topo.Node.is_team_leader)
}

// string team = 6;
inline void Node::clear_team() {
  _impl_.team_.ClearToEmpty();
}
inline const std::string& Node::team() const {
  // @@protoc_insertion_point(field_get:topo.Node.team)
  return _internal_team();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Node::set_team(ArgT0&& arg0, ArgT... args) {
 
 _impl_.team_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:topo.Node.team)
}
inline std::string* Node::mutable_team() {
  std::string* _s = _internal_mutable_team();
  // @@protoc_insertion_point(field_mutable:topo.Node.team)
  return _s;
}
inline const std::string& Node::_internal_team() const {
  return _impl_.team_.Get();
}
inline void Node::_internal_set_team(const std::string& value) {
  
  _impl_.team_.Set(value, GetArenaForAllocation());
}
inline std::string* Node::_internal_mutable_team() {
  
  return _impl_.team_.Mutable(GetArenaForAllocation());
}
inline std::string* Node::release_team() {
  // @@protoc_insertion_point(field_release:topo.Node.team)
  return _impl_.team_.Release();
}
inline void Node::set_allocated_team(std::string* team) {
  if (team != nullptr) {
    
  } else {
    
  }
  _impl_.team_.SetAllocated(team, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.team_.IsDefault()) {
    _impl_.team_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:topo.Node.team)
}

// repeated string neighbors = 7;
inline int Node::_internal_neighbors_size() const {
  return _impl_.neighbors_.size();
}
inline int Node::neighbors_size() const {
  return _internal_neighbors_size();
}
inline void Node::clear_neighbors() {
  _impl_.neighbors_.Clear();
}
inline std::string* Node::add_neighbors() {
  std::string* _s = _internal_add_neighbors();
  // @@protoc_insertion_point(field_add_mutable:topo.Node.neighbors)
  return _s;
}
inline const std::string& Node::_internal_neighbors(int index) const {
  return _impl_.neighbors_.Get(index);
}
inline const std::string& Node::neighbors(int index) const {
  // @@protoc_insertion_point(field_get:topo.Node.neighbors)
  return _internal_neighbors(index);
}
inline std::string* Node::mutable_neighbors(int index) {
  // @@protoc_insertion_point(field_mutable:topo.Node.neighbors)
  return _impl_.neighbors_.Mutable(index);
}
inline void Node::set_neighbors(int index, const std::string& value) {
  _impl_.neighbors_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:topo.Node.neighbors)
}
inline void Node::set_neighbors(int index, std::string&& value) {
  _impl_.neighbors_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:topo.Node.neighbors)
}
inline void Node::set_neighbors(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.neighbors_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:topo.Node.neighbors)
}
inline void Node::set_neighbors(int index, const char* value, size_t size) {
  _impl_.neighbors_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:topo.Node.neighbors)
}
inline std::string* Node::_internal_add_neighbors() {
  return _impl_.neighbors_.Add();
}
inline void Node::add_neighbors(const std::string& value) {
  _impl_.neighbors_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:topo.Node.neighbors)
}
inline void Node::add_neighbors(std::string&& value) {
  _impl_.neighbors_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:topo.Node.neighbors)
}
inline void Node::add_neighbors(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.neighbors_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:topo.Node.neighbors)
}
inline void Node::add_neighbors(const char* value, size_t size) {
  _impl_.neighbors_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:topo.Node.neighbors)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Node::neighbors() const {
  // @@protoc_insertion_point(field_list:topo.Node.neighbors)
  return _impl_.neighbors_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Node::mutable_neighbors() {
  // @@protoc_insertion_point(field_mutable_list:topo.Node.neighbors)
  return &_impl_.neighbors_;
}

// int32 max_inflight = 8;
inline void Node::clear_max_inflight() {
  _impl_.max_inflight_ = 0;
}
inline int32_t Node::_internal_max_inflight() const {
  return _impl_.max_inflight_;
}
inline int32_t Node::max_inflight() const {
  // @@protoc_insertion_point(field_get:topo.Node.max_inflight)
  return _internal_max_inflight();
}
inline void Node::_internal_set_max_inflight(int32_t value) {
  
  _impl_.max_inflight_ = value;
}
inline void Node::set_max_inflight(int32_t value) {
  _internal_set_max_inflight(value);
  // @@protoc_insertion_point(field_set:topo.Node.max_inflight)
}

// -------------------------------------------------------------------

// Topology

// repeated .topo.Node nodes = 1;
inline int Topology::_internal_nodes_size() const {
  return _impl_.nodes_.size();
}
inline int Topology::nodes_size() const {
  return _internal_nodes_size();
}
inline void Topology::clear_nodes() {
  _impl_.nodes_.Clear();
}
inline ::topo::Node* Topology::mutable_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:topo.Topology.nodes)
  return _impl_.nodes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::topo::Node >*
Topology::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:topo.Topology.nodes)
  return &_impl_.nodes_;
}
inline const ::topo::Node& Topology::_internal_nodes(int index) const {
  return _impl_.nodes_.Get(index);
}
inline const ::topo::Node& Topology::nodes(int index) const {
  // @@protoc_insertion_point(field_get:topo.Topology.nodes)
  return _internal_nodes(index);
}
inline ::topo::Node* Topology::_internal_add_nodes() {
  return _impl_.nodes_.Add();
}
inline ::topo::Node* Topology::add_nodes() {
  ::topo::Node* _add = _internal_add_nodes();
  // @@protoc_insertion_point(field_add:topo.Topology.nodes)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::topo::Node >&
Topology::nodes() const {
  // @@protoc_insertion_point(field_list:topo.Topology.nodes)
  return _impl_.nodes_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace topo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_topology_2eproto
